fun main(){
    //Exercici 1
    println("Exercici 1")
    var l1:Lampada = Lampada("Menjador",true)
    l1.encendreLampada()
    println()
    l1.canviarColor()
    l1.canviarColor()
    l1.canviarColor()
    println()
    l1.augmentarIntensitat()
    l1.augmentarIntensitat()
    l1.augmentarIntensitat()
    l1.augmentarIntensitat()
    println()

    //Exercici 2
    println("Exercici 2")
    var l2:Lampada = Lampada("Cuina",false)
    l2.encendreLampada()
    println()
    l2.canviarColor()
    l2.canviarColor()
    println()
    l2.augmentarIntensitat()
    l2.augmentarIntensitat()
    l2.augmentarIntensitat()
    l2.augmentarIntensitat()
    println()
    l2.apagarLampada()
    println()
    l2.canviarColor()
    println()
    l2.encendreLampada()
    println()
    l2.canviarColor()
    println()
    l2.augmentarIntensitat()
    l2.augmentarIntensitat()
    l2.augmentarIntensitat()
    l2.augmentarIntensitat()


}